pub mod plugin;
pub mod models;
pub mod training;
pub mod model_selector;
pub mod mlp_config;
pub mod rbf_config;
pub mod svm_config;
pub mod model_manager_ui;
mod image_classifier;
pub(crate) mod menu;
pub(crate) mod game_classifier;